### ISSUE TITLE
你好，我复制你的项目执行action时一直失败，可否帮我看一下怎么回事

### ISSUE THREAD

**Issue by wartaiwan24** [fordes123/adg-rule#36]
![图片](https://github.com/user-attachments/assets/e9155321-b7e6-40c8-8c44-1cc517cf7003)
https://github.com/wartaiwan24/ShuraAdguardRule

**Comment by fordes123** [comment]
> ![图片](https://private-user-images.githubusercontent.com/189248817/388580479-e9155321-b7e6-40c8-8c44-1cc517cf7003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzc3OTcsIm5iZiI6MTczMjIzNzQ5NywicGF0aCI6Ii8xODkyNDg4MTcvMzg4NTgwNDc5LWU5MTU1MzIxLWI3ZTYtNDBjOC04YzQ0LTFjYzUxN2NmNzAwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwMTA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjY4NjhjNzRlZWExYzMyYjQyNzgxOWRhODA0NDkwNWQ2MDU5YWM0ODgwNjQ5ZjcwOTZhZmY3MjVhMTg4NjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qYTQwLcmk0MOZL3KN6wUe360fiKyFyw-LTtUEA6j0vE) https://github.com/wartaiwan24/ShuraAdguardRule

配置文件 第 83-263 行缩进少了一个空格

**Comment by wartaiwan24** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/189248817/388580479-e9155321-b7e6-40c8-8c44-1cc517cf7003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzc3OTcsIm5iZiI6MTczMjIzNzQ5NywicGF0aCI6Ii8xODkyNDg4MTcvMzg4NTgwNDc5LWU5MTU1MzIxLWI3ZTYtNDBjOC04YzQ0LTFjYzUxN2NmNzAwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwMTA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjY4NjhjNzRlZWExYzMyYjQyNzgxOWRhODA0NDkwNWQ2MDU5YWM0ODgwNjQ5ZjcwOTZhZmY3MjVhMTg4NjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qYTQwLcmk0MOZL3KN6wUe360fiKyFyw-LTtUEA6j0vE) https://github.com/wartaiwan24/ShuraAdguardRule
> 
> 配置文件 第 83-263 行缩进少了一个空格

多谢 问题已解决
