### ISSUE TITLE
不错的项目，提两个小问题。。。

### ISSUE THREAD

**Issue by hululu1068** [fordes123/adg-rule#4]
不错的项目，解决了目前AdguardHome规则太多，严重重复的问题。。。
有两个小问题：
1. `NoTrack Tracker Blocklist`的规则合并了没作任何处理（我没用）
<img width="558" alt="image" src="https://user-images.githubusercontent.com/68652362/201516725-b777744c-ae3f-4a9e-8c33-2ed651f47e4a.png">
2. 运行提示`Node.js 12`即将停用,`set-output`即将不受支持。不过不要紧.
<img width="706" alt="image" src="https://user-images.githubusercontent.com/68652362/201516785-ca45d5d1-161e-40e6-86b6-1f04df346315.png">

再次感谢大佬！@ fordes123

**Comment by fordes123** [comment]
首先感谢反馈~

1. 需要明确 **本程序不会对规则进行任何修改，只是去重和分类（会剔除无效规则）**
此外，你截图的这些规则都是正确的域名拦截规则，这一点可以参考 AdGuardHome [官方文档](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists) 以下为部分引用：
> `example.org`: a simple domain rule. Blocks domain but not its subdomains. remains allowed.`example.org` `www.example.org`

2. 两个警告问题已处理
